version: '3.5'

services:
  kotlin-restful-api:
    container_name: api
    image: api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_URL: jdbc:postgresql://api:5432/api
  kotlin-restful-api-postgres:
    container_name: "api"
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres